[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

[package]
name = "Serde"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ex01"
path = "ex01.rs"

[[bin]]
name = "ex02"
path = "ex02.rs"

[[bin]]
name = "ex03"
path = "ex03.rs"

